Добавляет разметку главной страницы
htmlacademy-adaptive/1375337-cat-energy-24 pull request #2
Opened 2021-11-27 16:19 UTC by LomaevaVV

2021-11-27 18:07 UTC, wrgraff requested changes
Хорошая работа.
Если смущают смайлики, отмечающие каждый комментарий -- почитай в шпаргалках правила ревью =)

2021-11-27 18:07 UTC, wrgraff commented on source/index.html
> +              <p class="principles__descriprion">
Элемент списка уже и сам содержит текстовый контент, не обязательно делать еще и параграф.
Разве что ты предполагаешь, что в этом тексте может быть несколько абзацев

2021-11-27 18:07 UTC, wrgraff commented on source/index.html
> +          <ul class="example__result result">
Здесь парные значения, поэтому хорошо бы подошел список `<dl>`

2021-11-27 19:20 UTC, LomaevaVV commented on source/index.html
> +    <!-- Шапка -->
Мне так симпатичнее)))) Ну Шапку убрала, согласна. Остальное оставила, мне так удобнее.

2021-11-27 19:22 UTC, LomaevaVV commented on source/index.html
> +              <a class="navigation__link navigation__link--current" href="#"
ок, поставлю везде ссылки, учту. просто в курсе по первой верстке делали заглушки именно в на карент страницы - Шабалин так учил)))))))))))))

2021-11-27 19:25 UTC, LomaevaVV commented on source/index.html
> +      <h1 class="page-main_visually-hidden visually-hidden">Кэт энерджи</h1>
сначала был просто visually-hidden, потом догнали пчелы со своим БЭМом и подумалось что по БЭМу надо так)))))))))))))))

2021-11-27 19:31 UTC, LomaevaVV commented on source/index.html
> +            src="../source/img/logo/logo_icon_mobile.svg"
это я чет ступила.

2021-11-27 19:33 UTC, LomaevaVV commented on source/index.html
> +          <a href="program-selection.html" class="program__button button"
сделала, согласна. Реализую страницы - вставлю ссылки.

2021-11-27 19:34 UTC, LomaevaVV commented on source/index.html
> +          >
Prettier - да. Знать бы еще как его настроить, изучу вопрос. Отформатировала Beautify - вроде лучше. А ты чем советуешь пользоваться?

2021-11-27 19:35 UTC, LomaevaVV commented on source/index.html
> +              <p class="principles__descriprion">
это я чет заморочилась, согласна

2021-11-27 19:37 UTC, LomaevaVV commented on source/index.html
> +          <ul class="example__result result">
точно! Я про определения забыла совсем.

2021-11-27 19:42 UTC, LomaevaVV commented on source/index.html
> +            alt="Cat energy"
плохо знакома на самом деле с aria-hidden="true", сделала так. Спасибо за подсказку.

2021-11-27 23:33 UTC, wrgraff commented on source/index.html
> +            alt="Cat energy"
Он просто из доступности скрывает контент

2021-11-27 23:33 UTC, wrgraff commented on source/index.html
> +    <!-- Шапка -->
Я прост спросил =)
Можно было не убирать. Это просто вопрос! ))

2021-11-27 23:39 UTC, wrgraff commented on source/index.html
> +              <a class="navigation__link navigation__link--current" href="#"
Не могло такого быть, заглушка никак не может стоять на текущую страницу.

Это единственный вариант, который будет ошибкой. Ссылка или есть, и тогда она должна быть верной, или ее нет вовсе вместе с атрибутом.

Вот код из Барбершопа:
```
<ul class="navigation-list">
  <li class="navigation-item">
    <a class="navigation-link" href="about.html">О нас</a>
  </li>
  <li class="navigation-item">
    <a class="navigation-link navigation-link-current" href="catalog.html">Каталог</a>
  </li>
  <li class="navigation-item">
    <a class="navigation-link" href="faq.html">Частые вопросы</a>
  </li>
</ul>
```

2021-11-27 23:42 UTC, wrgraff commented on source/index.html
> +      <h1 class="page-main_visually-hidden visually-hidden">Кэт энерджи</h1>
Чуть меньше всяких Романов слушать надо в чатах )

2021-11-27 23:55 UTC, wrgraff commented on source/index.html
> +          <a href="program-selection.html" class="program__button button"
Так не реализуешь же, этой страницы и не будет никогда

2021-11-27 23:55 UTC, wrgraff commented on source/index.html
> +          >
А я ничем не пользуюсь )

2021-11-27 23:58 UTC, wrgraff commented on source/index.html
> +              <p class="principles__descriprion">
Это тоже нормальный подход, вопрос был в том, насколько осознанный

2021-11-27 23:58 UTC, wrgraff approved these changes

2021-11-27 23:58 UTC, merged

2021-11-28 07:32 UTC, LomaevaVV commented on source/index.html
> +              <a class="navigation__link navigation__link--current" href="#"
Значит я тупила,  почему-то так запомнила. И главное у меня седона так сдана)))))) И в индексе и в каталоге у текущей страницы # в ссылке. В общем, запомню, спасибо)

2021-11-28 09:10 UTC, wrgraff commented on source/index.html
> +              <a class="navigation__link navigation__link--current" href="#"
Если сдана, это ещё не значит, что там все правильно ))