Добавляет разметку внутренних cтраниц
htmlacademy-adaptive/1375337-cat-energy-24 pull request #3
Opened 2021-11-28 13:56 UTC by LomaevaVV

2021-11-28 21:33 UTC, wrgraff requested changes

2021-11-28 21:33 UTC, wrgraff commented on source/catalog.html
> +            <a class="navigation__link navigation__link--current" href="index.html">Главная</a>
Копировать код тоже надо внимательно!
Активная страница здесь — не главная =)

Как и на странице формы:
https://github.com/htmlacademy-adaptive/1375337-cat-energy-24/blob/5b5d07ca898f3f6fc8c053abd319f6ae423690aa/source/form.html#L26

2021-11-28 21:33 UTC, wrgraff commented on source/catalog.html
> +          <h3 class="product-title">Cat Energy PRO 500 г</h3>
А ссылки на саму карточку товара тут не предполагается?
[По пункту ТЗ 6.1](https://up.htmlacademy.ru/adaptive/24/project/cat-energy#cat-energy-6-1) должно быть

2021-11-28 21:33 UTC, wrgraff commented on source/catalog.html
> +          <img class="product__image" src="img/catalog/cat_energy_chicken_small.png" width="68" height="86" alt="Cat Energy PRO Курица 500 г" tabindex="0" />
А с какой целью здесь `tabindex="0"`?

2021-11-28 21:33 UTC, wrgraff commented on source/catalog.html
> +        <div class="extra__product product product--extra">
Смотри, БЭМ — это про оформление. 2 части интерфейса могут быть очень связаны по смыслу: продукт и дополнительный продукт. Но есть ли что-то общее в том, как они представлены (особенно если посмотреть на десктопную версию)?
![изображение](https://user-images.githubusercontent.com/37917037/143786322-cdc7e0f0-e962-4467-a13d-9d44211f04a5.png)
![изображение](https://user-images.githubusercontent.com/37917037/143786329-0954e0f2-65f8-4ff7-849c-5a1c0ee127ae.png)

Разница огромна!
Представь, каково тебе будет все это переписывать всего лишь через модификатор. Он будет менять полностью сетку, отступы, размеры элементов...

Так вот, БЭМ — это про оформление. Если у нас есть 2 похожие кнопки — одна отправляет ракету в космос, а другая издает звук "бип", то они будут одним блоком, потому что они похожи.
А если у нас 2 кнопки, делающие одно действие, но одна выглядит как кнопка, а другая — как кружок с иконкой, то это будут 2 разных блока.

2021-11-28 21:33 UTC, wrgraff commented on source/catalog.html
> +        <h2 class="extra__title">Дополнительные товары</h2>
Ну вот доп товары можно бы и в список разместить, конечно.
Никаких чужеродных элементов среди них нет же.

2021-11-28 21:33 UTC, wrgraff commented on source/form.html
> +      <h1 class="page-main__title title">Подбор программы</h1>
Хорошо, что заголовки выделила как один и тот же элемент для разных страниц

2021-11-28 21:33 UTC, wrgraff commented on source/form.html
> +          <legend class="fieldset__legend visualy-hidden">Данные кота</legend>
А если блок скрыт — зачем ему класс элемента?
Вдруг он вообще что-то перепишет из стилей легенды и она еще и видимой станет?

2021-11-28 21:33 UTC, wrgraff commented on source/form.html
> +            </li>
Ты точно уверена, что хочешь разметить текстовое поле с подписью и чекбокс одним и тем же БЭМ-блоком?
Достаточно ли они похожи друг на друга?
![изображение](https://user-images.githubusercontent.com/37917037/143786724-b6ddfb12-ba88-4ff3-8570-f6ca627841dd.png)
![изображение](https://user-images.githubusercontent.com/37917037/143786728-ab128ec5-cd11-4e72-8ff1-7de1e0cf2d46.png)

Дело твое, конечно (тебе ж страдать с этим).
[Но я бы так делать не рекомендовал](https://youtube.com/playlist?list=PL6xpnt2woRKk0btmfzM2oR6-ste7wZUWm) =)

2021-11-28 21:33 UTC, wrgraff commented on source/form.html
> +              <span class="control-mark"></span>
А это вообще что за блок и почему он отдельно от всех?

2021-11-28 21:33 UTC, wrgraff commented on source/form.html
> +            <textarea class="fieldset__textarea">Расскажите обо всех повадках кота</textarea>
Это ведь тоже поле. Но оно осталось без лейбла

2021-11-28 21:33 UTC, wrgraff commented on source/form.html
> +          <legend class="fieldset__legend visualy-hidden">Дополнительно</legend>
А почему скрыта легенда?
Она же есть на макете. Посмотри внимательнее какие легенды скрыты, а какие нет

2021-11-29 06:47 UTC, LomaevaVV commented on source/catalog.html
> +            <a class="navigation__link navigation__link--current" href="index.html">Главная</a>
вот вы проверяющие - глазастые!!! Спасибо, сори что не перепроверила)

2021-11-29 07:02 UTC, LomaevaVV commented on source/catalog.html
> +          <h3 class="product-title">Cat Energy PRO 500 г</h3>
Вот была она у меня изначально, зачем стерла не знаю)))) Сделано!

2021-11-29 07:05 UTC, LomaevaVV commented on source/catalog.html
> +          <img class="product__image" src="img/catalog/cat_energy_chicken_small.png" width="68" height="86" alt="Cat Energy PRO Курица 500 г" tabindex="0" />
Убрала. Заранее ненужную соломку подкладывала, типа чтобы можно было табом на картинку переходить. Но в этом проекте и так картинка в ссылке. тут это не надо.

2021-11-29 07:06 UTC, LomaevaVV commented on source/catalog.html
> +        <div class="extra__product product product--extra">
Вот я долго гипнотизировала эти формы, подкупало что оформление текста и кнопок одинаковое и подумала ладно, сделаю одинаковые и потом разберусь когда стилизовать начну. Но лучше сразу не мучаться, согласна.

2021-11-29 07:31 UTC, LomaevaVV commented on source/catalog.html
> +        <h2 class="extra__title">Дополнительные товары</h2>
Ок, пусть списком)

2021-11-29 07:44 UTC, LomaevaVV commented on source/form.html
> +          <legend class="fieldset__legend visualy-hidden">Данные кота</legend>
ок, не буду миксовать когда visually hidden

2021-11-29 07:48 UTC, LomaevaVV commented on source/form.html
> +              <span class="control-mark"></span>
По стайлгайду посмотрела, стандартные радиобаттоны/чекбоксы не подойдут. Надо будет прорисовать свои. Вот завела класс для прорисовки, а сам инпут сделала visually-hidden

2021-11-29 07:52 UTC, LomaevaVV commented on source/form.html
> +              <span class="control-mark"></span>
ой, но не по БЭМу завела. поправлю, ок

2021-11-29 07:55 UTC, LomaevaVV commented on source/form.html
> +          <legend class="fieldset__legend visualy-hidden">Дополнительно</legend>
Думаю, невнимательный копи-паст)))) Спасибо, что заметил!

2021-11-29 08:06 UTC, LomaevaVV commented on source/form.html
> +            </li>
Изменила. Сознательно сделала для радиобаттонов и чекбоксов один бэм элемент. Так посмотрю при оформлении, думаю что получится детализировать стили по типу инпута. Ну там уже чуть что изменю или модификатор добавлю.

2021-11-29 08:13 UTC, LomaevaVV commented on source/form.html
> +              <span class="control-mark"></span>
Но можно было наверное и псевдоэлементом делать поддельный чекбокс. Но шабалин в первом курсе учил так, я так и сделала опять))))

2021-11-29 08:59 UTC, wrgraff commented on source/catalog.html
> +           <dl class="product__feature feature">
Следи за отступами )
Сейчас у нас запускается тестирование и твоя разметка тест не прошла:
![изображение](https://user-images.githubusercontent.com/37917037/143837090-351f6687-3a0f-465a-b822-1ca63465cd9e.png)

![изображение](https://user-images.githubusercontent.com/37917037/143837151-fd41e7a1-3bfe-4041-b944-2e43f4f2d1c1.png)

2021-11-29 08:59 UTC, wrgraff commented on source/catalog.html
> +          <img class="product__image" src="img/catalog/cat_energy_chicken_small.png" width="68" height="86" alt="Cat Energy PRO Курица 500 г" tabindex="0" />
А если картинка будет не в ссылке — зачем нужна возможность на нее переходить?
Вот мы сфокусировались на картинке. Она не интерактивна. Перейти по ней нельзя. Нажать нельзя. Зачем эта фокусировка нужна?
Так ты обманешь пользователя: он будет думать, что можно что-то сделать, а сделать ничего нельзя.

2021-11-29 09:01 UTC, wrgraff commented on source/catalog.html
> +        <div class="extra__product product product--extra">
Кнопки и тексты да, но вот сетка совсем разная.
Вкупе еще и с перестройкой при адаптиве будет сложно.

2021-11-29 09:05 UTC, wrgraff commented on source/catalog.html
> +            <a class="product-extra__link" href="#">
Кажется, потерялся блок `.product-extra`

2021-11-29 09:05 UTC, wrgraff commented on source/form.html
> +              <span class="control-mark"></span>
Я пришел к выводу, что в барбершопе это дает возможность сделать крестик через псевдоэлементы.
Если у нас не такой по виду чекбокс, то это может и не иметь смысла

2021-11-29 09:06 UTC, wrgraff commented on source/form.html
> +          <legend class="fieldset__legend visualy-hidden">Данные кота</legend>
Это не просто так в форме вопроса )
Есть ситуация, когда это помогает. Например, когда нужно по классу элемента стилизовать следующий элемент (как в чекбоксах).
Правда, там вообще хочется уйти наоборот уже от `visually-hidden`

2021-11-29 09:09 UTC, wrgraff requested changes

2021-11-29 09:09 UTC, wrgraff commented on source/form.html
> +      <form action="https://echo.htmlacademy.ru/" method="get" class="page_main__form form">
```suggestion
      <form action="https://echo.htmlacademy.ru/" method="get" class="page-main__form form">
```

2021-11-29 11:07 UTC, LomaevaVV commented on source/catalog.html
> +          <img class="product__image" src="img/catalog/cat_energy_chicken_small.png" width="68" height="86" alt="Cat Energy PRO Курица 500 г" tabindex="0" />
Да это в седоне была нужна, там по фокусу просили затемнять. Ну и чет оно ко мне прилипло. Поняла, не буду лепить куда не надо)))) Согласна, что лишний раз точно не надо лепить табиндекс. Если уж понадобится, то во время стилизации прилепить можно. но точно не заранее.

2021-11-29 11:10 UTC, LomaevaVV commented on source/catalog.html
> +           <dl class="product__feature feature">
слушай, они же должнф автоматом норм ставиться? или я где-то руками накосячила? буду стараться. Визуально то не видно особо...

2021-11-29 11:13 UTC, LomaevaVV commented on source/catalog.html
> +            <a class="product-extra__link" href="#">
да, рукалицо...

2021-11-29 11:15 UTC, LomaevaVV commented on source/form.html
> +      <form action="https://echo.htmlacademy.ru/" method="get" class="page_main__form form">
да, косяк

2021-11-29 11:20 UTC, LomaevaVV commented on source/form.html
> +              <span class="control-mark"></span>
ок. Пока оставила, буду стилизовать, уберу может.

2021-11-29 11:35 UTC, wrgraff commented on source/catalog.html
> +          <img class="product__image" src="img/catalog/cat_energy_chicken_small.png" width="68" height="86" alt="Cat Energy PRO Курица 500 г" tabindex="0" />
Кого затемнять по фокусу?
При стилизации табиндексов тоже не должно появляться! При правильной разметке у тебя все интерактивные элементы будут размечены такими тегами, которые уже фокусируются.

Добавление табиндекса это оживление элемента, который не был интерактивным. Нужно точно знать зачем и почему это делается, не может быть чтобы это было просто ради внешнего вида.

2021-11-29 11:37 UTC, wrgraff commented on source/catalog.html
> +           <dl class="product__feature feature">
Редактор помогает ставить отступы правильно, но сделать их неправильными он тоже вполне себе позволит =)

2021-11-29 11:39 UTC, wrgraff requested changes

2021-11-29 11:39 UTC, wrgraff commented on source/catalog.html
> +<body class="page_body">
Эээ. Что это? )
Был элемент, а теперь?

2021-11-29 12:08 UTC, LomaevaVV commented on source/catalog.html
> +          <img class="product__image" src="img/catalog/cat_energy_chicken_small.png" width="68" height="86" alt="Cat Energy PRO Курица 500 г" tabindex="0" />
вообще согласна. Но там я реально им сделала, но видимо картинка должна была быть в ссылке. Учту.

2021-11-29 12:10 UTC, merged