Добавляет базовую стилизацию всех страниц
htmlacademy-adaptive/1375337-cat-energy-24 pull request #4
Opened 2021-12-02 20:35 UTC by LomaevaVV

2021-12-03 13:15 UTC, wrgraff requested changes
Я тебе еще ролик небольшой в Телеграм отправлю, кое-что важно было показать визуально

2021-12-04 11:48 UTC, LomaevaVV commented on source/catalog.html
> +          <a href="#" class="product__button button button--catalog button button--catalog--catalog">Заказать</a>
Посмеялась)))))))) автозаменой стили правила и что-то пошло не так

2021-12-04 11:51 UTC, LomaevaVV commented on source/index.html
> +            <span class="program-type__icon"></span>
охохох, постараюсь учесть) Это меня дискорд сбил, будь он неладен. Там кто-то выложил скрин, и там все это сделано было, и я чет решила что мне тоже надо)))

2021-12-04 12:14 UTC, LomaevaVV commented on source/index.html
> +            <span class="principles__icon"></span>
ок!

2021-12-04 12:36 UTC, wrgraff commented on source/index.html
> +            <span class="program-type__icon"></span>
Там и не такое могут выложить...

2021-12-04 12:37 UTC, wrgraff commented on source/catalog.html
> +          <a href="#" class="product__button button button--catalog button button--catalog--catalog">Заказать</a>
Да я так и понял, поэтому и коммент такой )

2021-12-04 12:42 UTC, LomaevaVV commented on source/sass/global/global.scss
> +}
+

2021-12-04 12:56 UTC, LomaevaVV commented on source/sass/global/global.scss
> +$show-more-title-color: #111111;
сделано. А это, кстати, на лекции было. Но не подчеркнули это, а просто в потоке делали и я как-то не учла.

2021-12-04 13:26 UTC, LomaevaVV commented on source/sass/blocks/principles.scss
> +  min-width: 50px;
Я там если пишу 50px, почему-то половинчатая ширина отображается, а если писала min-width, то красиво было))) Ладно, потом при тщательной проработке решу

2021-12-04 13:27 UTC, LomaevaVV commented on source/sass/blocks/principles.scss
> +  min-width: 50px;
про то, что так как я это решила делать не надо - я поняла, и понимаю почему. Если ширина зашита железно, то так и должно быть...

2021-12-04 13:32 UTC, LomaevaVV commented on source/sass/blocks/program.scss
> +  background-image: url("..//img/index/index-background.jpg");
ок, учту.

2021-12-06 10:56 UTC, LomaevaVV commented on source/sass/global/global.scss
> +$example-border-color: #cdcdcd;
Сделала, надеюсь так норм) серый почти весь диапазон занял, ужас)))))))))

2021-12-06 11:03 UTC, LomaevaVV commented on source/sass/blocks/contacts.scss
> +  justify-content: start;
согласна.

2021-12-06 11:12 UTC, LomaevaVV commented on source/sass/blocks/contacts.scss
> +  font-family: "Oswald", sans-serif;
Сделано

2021-12-06 13:10 UTC, LomaevaVV commented on source/sass/blocks/fieldset.scss
> +  border: 0 none;
согласна, не знаю почему вдруг 0 у меня образовался там)

2021-12-06 13:13 UTC, LomaevaVV commented on source/sass/blocks/fieldset.scss
> +.fieldset__checkbox:not(:last-child) {
согласна - не задумывалась.

2021-12-06 13:19 UTC, LomaevaVV commented on source/sass/blocks/navigation.scss
> +  bottom: -205px;
((( ок, обмозгую этот момент когда будем делать. Заскринила себе в записки

2021-12-06 13:19 UTC, LomaevaVV commented on source/sass/blocks/navigation.scss
> +  // Position закоментирован для тек удобства работы!
убрала -понятно.

2021-12-07 06:33 UTC, LomaevaVV commented on source/sass/blocks/navigation.scss
> +  color: inherit;
ок! постараюсь запомнить)

2021-12-07 06:37 UTC, LomaevaVV commented on source/sass/blocks/page-header.scss
> +  flex-wrap: wrap;
принято

2021-12-07 06:54 UTC, LomaevaVV commented on source/sass/blocks/page-header.scss
> +  max-height: 40px;
принято

2021-12-07 07:05 UTC, LomaevaVV commented on source/sass/blocks/page-main.scss
> +.page-main:nth-child(n):not(:last-child) {
Поняла ошибку. Ок.

2021-12-07 07:12 UTC, LomaevaVV commented on source/sass/blocks/result.scss
> +.result__name--low {
согласна, заведу отдельный стиль. Все-таки сильное различие.

2021-12-07 07:52 UTC, LomaevaVV commented on source/sass/blocks/page-footer.scss
> +  grid-template-columns: 281px;
это трудно))))))))))))))))))) Отступы вообще все неровные. Но размер крупного блока наверное да, должен быть целым.

2021-12-07 11:21 UTC, LomaevaVV commented on source/sass/global/global.scss
> +  width: 320px;
+

2021-12-07 11:22 UTC, LomaevaVV commented on source/sass/blocks/fieldset.scss
> +  max-width: 190px;
постараюсь учесть

2021-12-07 18:39 UTC, wrgraff commented on source/sass/global/global.scss
> +$example-border-color: #cdcdcd;
В чем прелесть: можно всегда найти место новому оттенку, потому что даже между `gray-100` и `gray-200` куча точек

2021-12-07 18:46 UTC, wrgraff commented on source/sass/blocks/page-footer.scss
> +  grid-template-columns: 281px;
Делай пока ровнее =)

2021-12-07 18:52 UTC, wrgraff commented on source/sass/blocks/principles.scss
> +  min-width: 50px;
Видимо, на формирование ширины что-то влияет внутри элемента.
И по сути при минимальной ширине что-то изнутри растягивает элемент... Надо посмотреть что к чему, но так я бы навсидку грешил на [box-sizing](https://frontend-design.notion.site/box-sizing-74c2b981a9624d03ba122967a529b9ad)

2021-12-07 18:59 UTC, wrgraff requested changes
Все хорошо, но следи за тем, чтобы тесты проходили. Проще исправлять сразу, чем накопить ошибки.
<img width="861" alt="изображение" src="https://user-images.githubusercontent.com/37917037/145089645-b9ab5715-b1ac-431d-ade9-2a91a5ef543b.png">

Ты можешь проверить проходит ли тестирование не только по ГитХабу, но и запустить локально `npm test`.

2021-12-07 19:33 UTC, wrgraff approved these changes

2021-12-07 19:34 UTC, merged