Добавляет сетки на главную страницу
htmlacademy-adaptive/1375337-cat-energy-24 pull request #5
Opened 2021-12-14 09:38 UTC by LomaevaVV

2021-12-15 10:45 UTC, wrgraff requested changes

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/images.scss
> +  grid-template-areas: "images" "toggle";
Что-то непонятно, зачем тут именованные области. Это как-то ту мач.
Они удобны в перестроениях сложных, очень помогают сделать наглядно сетку. Но тут то 2 всего )

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/navigation.scss
> +    display: flex;
Когда при смене разрешения грид меняется на флекс — это повод задуматься.
Не то чтобы это ошибка, просто реально сетки обычно не настолько разные. Особенно хорошо делать одну раскладку, чтобы добавлять более мелкие брейкпоинты для резиновой верстки.

В данном случае вот я пришел к выводу, что грид, который задан изначально, ничего не делает в общем то =) Его отключение прям не меняет ничего. Зачем он?

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/navigation.scss
> +  word-break: break-word;
У тебя в принципе не должно происходить что-то такое:
![изображение](https://user-images.githubusercontent.com/37917037/146166642-d8b7d7a2-9fac-43a9-8082-f54975cbb7e1.png)
Например, тут на скрине видно, что ты не ограничила ширину сайта (он не должен сжиматься меньше 320). Тогда и тексту бы так переноситься не было бы нужды

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/wrapper.scss
> +  margin: 0 auto;
Размера то у оберток нет, в результате они не центрируются. А должны хотя бы на самом большом экране центрировать контент.
А сейчас вот так:
![изображение](https://user-images.githubusercontent.com/37917037/146167327-f6ef044a-9b71-4bd1-9a86-835aa275030b.png)

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/wrapper.scss
> +  box-sizing: border-box;
Это правило [рекомендую использовать глобально](https://frontend-design.notion.site/box-sizing-74c2b981a9624d03ba122967a529b9ad)

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/wrapper.scss
> +    margin: 0;
Он перестанет центрировать, если так сбросить отступы

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/wrapper.scss
> +    padding: 0 70px;
Можно рассмотреть вариант с разными отступами для оберток-элементов

2021-12-15 10:45 UTC, wrgraff commented on source/sass/global/global.scss
> +    background-size: 50% 696px;
Так у тебя одна сторона тянется, а другая фиксируется. И картинка искажается.
Допустимое искажение картинок в пределах 5% где-то. Так что лучше оставь фиксированный размер.
Фон потом рисуется градиентом.

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/result.scss
> +    display: grid;
Получается, что просто чтобы ставить текст в строку или в столбик ты аж целую раскладку меняешь с грида на флекс.
Попробуй сделать это в рамках сетки одного типа

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/program.scss
> +    grid-template-columns: 1fr 1.3fr;
Ты прям думаешь идеально вычислила соотношение? )
Картинка то там вообще пересекается с текстом:
![изображение](https://user-images.githubusercontent.com/37917037/146170021-a9f23abf-dc87-4b0d-bdcc-5be41bb649d7.png)

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/program.scss
> +    grid-template-columns: 1fr 1.3fr;
Если очень хочется использовать грид, можно попробовать многослойный применить

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/program.scss
> +    width: 244px;
А что, если текста станет больше или меньше, как кнопка должна себя повести?

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/program-type.scss
> +    grid-template-columns: 1.5fr 1fr;
Я бы сказал, что иконка вряд ли пропорционально меняет размер, она должна быть фиксирована по ширине

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/program-type.scss
> +  }
Но ведь грид вполне позволяет перестроить сетку так, чтобы иконка была то у заголовка, то справа на карточке.
Рисовать иконку то тут, то там — как-то не оптимально

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/principles.scss
> +    grid-template-columns: repeat(auto-fill, 230px);
Колонки должны растягиваться, а если становятся меньше, то — перестраиваться.
```suggestion
    grid-template-columns: repeat(auto-fill, minmax(230px, 1fr));
```

Такое правило заставит колонки не сжиматься меньше 230 точек и растягиваться если есть место.
Но. Важно ограничение по ширине у сайта, потому что иначе у тебя станет 5 колонок, потом 6, потом 7...

Или использовать `auto-fit`, а не `auto-fill`

2021-12-15 10:45 UTC, wrgraff commented on source/sass/blocks/principles.scss
> +    width: 230px;
Ширину определяет сетка, не нужно ее в элемент писать

2021-12-15 11:56 UTC, LomaevaVV commented on source/index.html
> +        <h2 class="program__title">Функциональное питание&nbspдля&nbspкотов</h2>
Исправила, спс

2021-12-15 12:06 UTC, LomaevaVV commented on source/sass/style.scss
>  // Index
согласна. Я про это подумала когда группировала, но потом подумала что мне все равно удобнее будет. уберу, все равно не туда смотрю когда нужный блок ищу, а в html.

2021-12-15 12:08 UTC, LomaevaVV commented on source/sass/style.scss
> +// Blocks
))

2021-12-15 13:17 UTC, LomaevaVV commented on source/sass/blocks/contacts.scss
> +    grid-area: contacts;
это я сначала гридом делала расположение контактов поверх карты, потом передумала уже не помню почему и сделала абсолютом. А след остался)

2021-12-16 07:27 UTC, LomaevaVV commented on source/sass/blocks/navigation.scss
> +  word-break: break-word;
чет упустила этот момент, ага. Хотя сейчас кажется на лекции упоминали. Спс.

2021-12-16 07:38 UTC, LomaevaVV commented on source/sass/blocks/button.scss
> +  word-break: break-word;
ок.

2021-12-16 07:47 UTC, LomaevaVV commented on source/index.html
> +          <div class="result__in-row">
как же меня бесит этот кусок разметки)))))))))))))))))))) разделила на два списка, надеюсь так ок.

2021-12-16 08:37 UTC, LomaevaVV commented on source/sass/blocks/images.scss
> +  grid-template-areas: "images" "toggle";
сделано

2021-12-16 08:38 UTC, LomaevaVV commented on source/sass/blocks/navigation.scss
> +    display: flex;
ок, буду внимательнее. Согласна, что глупо менять тип дисплэя с грид на флекс или наоборот.

2021-12-16 08:39 UTC, LomaevaVV commented on source/sass/blocks/wrapper.scss
> +  margin: 0 auto;
ограничила ширину body 320-1440

2021-12-16 09:13 UTC, LomaevaVV commented on source/sass/global/global.scss
> +    background-size: 50% 696px;
Сделала. Картинка сейчас неверная стоит, поэтому некрасиво смотрится, я потом вставлю ту, что надо.

2021-12-16 09:19 UTC, LomaevaVV commented on source/sass/blocks/result.scss
> +    display: grid;
принято

2021-12-16 09:46 UTC, LomaevaVV commented on source/sass/blocks/program.scss
> +    grid-template-columns: 1fr 1.3fr;
да, я подумала что я это буду думать-править как лучше когда картинка верная будет. С такой мелкой сейчас в любом случае не понять... но подправила.

2021-12-16 09:54 UTC, LomaevaVV commented on source/sass/blocks/program.scss
> +    width: 244px;
изменила на min-height для возможного переполнения

2021-12-16 12:50 UTC, LomaevaVV commented on source/sass/blocks/program-type.scss
> +    grid-template-columns: 1.5fr 1fr;
согласна. да

2021-12-16 13:45 UTC, LomaevaVV commented on source/sass/blocks/principles.scss
> +    width: 230px;
да, согласна

2021-12-16 13:47 UTC, LomaevaVV commented on source/sass/blocks/principles.scss
> +    grid-template-columns: repeat(auto-fill, 230px);
спасибо

2021-12-17 00:24 UTC, wrgraff requested changes

2021-12-17 00:24 UTC, wrgraff commented on source/index.html
> +          <dl class="result__group result__group--cost">
А зачем нам тут список, если в нем только один пункт?..
_Что ты там писала про бесячий кусок разметки? =)_

2021-12-17 00:24 UTC, wrgraff commented on source/sass/global/variables.scss
> +$color-green-300 : rgba(104, 183, 56, 0.85);
Для `rgba` я бы переменные не заводил. Потому что в SASS можно делать так прям на месте: `rgba($color-green-400, 0.85)`.
Это довольно удобно, так как мы тогда можем хранить только цвета, без всякой прозрачности.
Ну и немного странно, что совсем разные по типу цвета в одной цветовой схеме оказались.

Ну и пробел перед двоеточием странный.

2021-12-17 00:24 UTC, wrgraff commented on source/sass/global/global.scss
> +  max-width: 1440px;
А вот этого делать нельзя. Ишь, простая какая )
Что, если у нас пользователь с экраном 1600? 1920? Как у них фон секций тянуться будет?

2021-12-17 00:24 UTC, wrgraff commented on source/sass/global/global.scss
> +    background-repeat: no-repeat, no-repeat;
Одно и то же значение можно и не повторять

2021-12-17 00:24 UTC, wrgraff commented on source/sass/global/global.scss
> +  max-width: 1440px;
Кроме того, обрати внимание, что у макета "уши" — 110 пикселей. Но они могут быть и меньше! То есть, мы можем и на 1340 показать десктопный сайт с "ушами" по 60 пикселей. или меньше )

В общем, есть повод и `$desktop-width` пересмотреть

2021-12-17 00:24 UTC, wrgraff commented on source/sass/blocks/wrapper.scss
> +    margin-left: 0;
Ну так тем более перестанет )))

2021-12-17 00:24 UTC, wrgraff commented on source/sass/blocks/program.scss
> +    width: 244px;
Измени лучше на формирование высоты через отступы, при чем желательно в блоке `.button`, а не здесь. А то у тебя какая-то странная безразмерная кнопка выходит )
Обычно, за размер отступов, если они разные, отвечает модификатор кнопки.

2021-12-17 07:48 UTC, LomaevaVV commented on source/sass/global/global.scss
> +    background-repeat: no-repeat, no-repeat;
ок!

2021-12-17 07:49 UTC, LomaevaVV commented on source/sass/global/variables.scss
> +$color-green-300 : rgba(104, 183, 56, 0.85);
спасибо! надо запомнить)

2021-12-17 08:20 UTC, LomaevaVV commented on source/sass/blocks/wrapper.scss
> +  box-sizing: border-box;
Сделано, ок!

2021-12-17 09:32 UTC, LomaevaVV commented on source/sass/global/global.scss
> +  max-width: 1440px;
сделала. Пришлось добавить доп врапперы.

2021-12-17 09:40 UTC, LomaevaVV commented on source/sass/blocks/program.scss
> +    width: 244px;
да, согласна, бардак

2021-12-17 09:55 UTC, LomaevaVV commented on source/index.html
> +          <dl class="result__group result__group--cost">
и все еще бесячий

2021-12-17 10:10 UTC, LomaevaVV commented on source/sass/blocks/wrapper.scss
> +    margin-left: 0;
я понимаю, но здесь мне и не надо выравнивание посередине. Тут сетка перестроилась. Обнулила для модификатора только. Если не так, то как лучше? Не пойму?

2021-12-17 13:16 UTC, wrgraff approved these changes

2021-12-17 13:33 UTC, wrgraff commented on source/sass/blocks/wrapper.scss
> +    margin-left: 0;
Хм, врапперы перемещаешь... Ну ладно, пусть так

2021-12-17 13:33 UTC, merged