Добавляет адаптивную сетку внутренних страниц
htmlacademy-adaptive/1375337-cat-energy-24 pull request #6
Opened 2021-12-20 19:41 UTC by LomaevaVV

2021-12-22 21:02 UTC, wrgraff requested changes

2021-12-22 21:02 UTC, wrgraff commented on source/sass/blocks/fieldset.scss
>    margin-bottom: 20px;
Отступ в блоке

2021-12-26 07:27 UTC, LomaevaVV commented on source/form.html
> +          <ul class="fieldset__list ">
спс

2021-12-26 08:18 UTC, LomaevaVV commented on source/index.html
> +    <section class="page-main__catalog-index">
да, невнимательно заменила. Ц меня оказалось два разных блока с одним именем, пришлось менять тут название. Исправила.

2021-12-26 08:18 UTC, LomaevaVV commented on source/sass/global/global.scss
> +.page__body--index {
ок. Сделано

2021-12-26 08:23 UTC, LomaevaVV commented on source/sass/blocks/extra.scss
>  .product-extra__link {
действительно, что это я

2021-12-26 08:29 UTC, LomaevaVV commented on source/sass/blocks/extra.scss
> +  margin-bottom: 35px;
да. затупила. Спасибо!

2021-12-26 11:23 UTC, LomaevaVV commented on source/sass/blocks/product-extra.scss
> +    // column-gap: auto;
Убрала. Ок.

2021-12-26 11:25 UTC, LomaevaVV commented on source/sass/blocks/program.scss
>    font-family: $Oswald;
и вторая font такая же. Заменила.

2021-12-26 11:29 UTC, LomaevaVV commented on source/sass/blocks/fieldset.scss
>    margin-bottom: 20px;
да( забываю пока

2021-12-26 11:35 UTC, LomaevaVV commented on source/sass/blocks/form-item.scss
> +  min-height: 46px;
согласна.

2021-12-26 11:36 UTC, LomaevaVV commented on source/sass/blocks/form-item.scss
> +  height: 100%;
да, убрала. Паддингами и содержимым теперь высота определяется.

2021-12-28 11:02 UTC, LomaevaVV commented on source/catalog.html
> +    <div class="page-header__wrapper-outer">
сделано, спасибо за подсказку. у меня почему-то было в голове что типа правильно центровку через врапперы обязательно организовывать...

2021-12-28 11:57 UTC, LomaevaVV commented on source/catalog.html
> +        <div class="catalog__product-wrapper">
да, это я чет заморочилась)))) погорячилась)

2021-12-28 12:00 UTC, LomaevaVV commented on source/sass/blocks/feature-extra.scss
> +  display: grid;
согласна.

2021-12-29 11:38 UTC, LomaevaVV commented on source/sass/blocks/feature-extra.scss
> +  display: grid;
Здесь сетку подправила по твоим советам. 

Основная сетка (товары и доп товары) красиво тянутся до определенной ширины. Когда товаров становится 5  общая концепция ломается. Дальше заморачиваться пока не буду. Это сложно.

2021-12-29 11:38 UTC, LomaevaVV commented on source/sass/blocks/feature-extra.scss
> +  display: grid;
![image](https://user-images.githubusercontent.com/88784054/147658517-31594a59-414f-4d72-a213-0a55e95858a0.png)

2021-12-29 11:39 UTC, LomaevaVV commented on source/sass/blocks/feature-extra.scss
> +  display: grid;
![image](https://user-images.githubusercontent.com/88784054/147658559-a981a453-f4d7-4d1a-9983-d43e49ca4643.png)

2021-12-29 11:44 UTC, LomaevaVV commented on source/sass/blocks/feature-extra.scss
> +  display: grid;
Но зато теперь при фиксированной ширине экстра-фичи встают как надо, а не криво.

2021-12-29 12:33 UTC, LomaevaVV commented on source/form.html
> +        <div class="contacts__text">
Вот здесь пока оставила как есть. Никак у меня не выходит нормально, откатила все изменения. Подумаю когда интеграцию с картами реализую. Короче, прими пока так, пожалуйста, но постараюсь переделать.

2021-12-29 12:35 UTC, LomaevaVV commented on source/catalog.html
> +      <div class="contacts__wrapper wrapper wrapper--contacts">
это надо еще подумать

2021-12-29 15:05 UTC, wrgraff commented on source/catalog.html
> +    <div class="page-header__wrapper-outer">
С одной стороны это недалеко от истины: единообразный подход лучше сохранять.
То есть, если у нас фон тянется в 2-х секциях из 6, то логично будет сделать обертку с центрированием во всех, чтобы они были единообразны. Хотя, можно было бы в 6 блоках без фона реализовать центрирование без обертки.

Но хэдер в любом случае по перестроениям и поведению заметно отличается, так что в нем можно и иначе поступить.

2021-12-29 15:06 UTC, wrgraff commented on source/catalog.html
> +        <div class="catalog__product-wrapper">
Если заморачиваются, то обычно как раз с попытками сделать как можно меньше элементов. Ради производительности

2021-12-29 15:11 UTC, wrgraff commented on source/index.html
> +      <ul class="navigation__list  navigation__list--index">
А тут 2 пробела
```suggestion
      <ul class="navigation__list navigation__list--index">
```

2021-12-29 15:11 UTC, wrgraff commented on source/sass/blocks/feature-extra.scss
> +  display: grid;
Да, с 5-ю подстава )
Но у нас все равно есть ограничение.
Да и один медиа-запрос можно добавить как вариант для ограничения максимального количества колонок. но это уже совсем нюансы

2021-12-29 15:12 UTC, wrgraff approved these changes

2021-12-29 15:12 UTC, merged