Добавляет декоративные элементы главной страницы
htmlacademy-adaptive/1375337-cat-energy-24 pull request #7
Opened 2022-01-03 13:32 UTC by LomaevaVV

2022-01-04 18:33 UTC, wrgraff requested changes
А что за странное название у файла `source/img/index/map pin.png.png?`
Пробелы в имени, да еще и дважды png

2022-01-04 18:33 UTC, wrgraff commented on source/catalog.html
> +  <script>
У такого меню должна быть логика, которая сейчас не соблюдается:

1. Оно должно быть работоспособным без js. Если скрипт не работает, меню должно быть в потоке (отталкивать контент), кнопка показа меню должна быть убрана
2. Если скрипт сработал, то меню должно быть по умолчанию закрытым
3. Если скрипт сработал и меню открыли, оно должно находиться вне потока: поверх контента (при отсутствии js так делать нельзя, так как меню тогда будет не скрыть и контент под ним окажется недоступными)

Пока все 3 условия в полной мере не выполняются.
Не то чтобы это важно в этом задании, но раз уж появился скрипт, то я описал проблемы.

2022-01-04 18:33 UTC, wrgraff commented on source/sass/blocks/principles.scss
> +    grid-template-columns: repeat(auto-fill, 230px);
А почему отказалась от растяжения?
Сейчас при некоторых вариантах выглядит странновато:
![изображение](https://user-images.githubusercontent.com/37917037/148105373-b852a285-7f4b-461f-9961-9819165f4629.png)

На самом деле, ты можешь просто с определенного разрешения (с десктопа) задать не автоматические колонки, а просто 4 колонки. Просто чтобы их не становилось 5

2022-01-04 18:33 UTC, wrgraff commented on source/sass/blocks/principles.scss
> +}
Вот картинки — они привязаны к логике, к содержанию элемента.
А цифры вряд ли должны при смене порядка следовать за элементом

2022-01-04 18:33 UTC, wrgraff commented on source/sass/blocks/principles.scss
> +    content: "1";
А что, если появится больше пунктов? Снова прописывать для них цифры?
Есть такая вещь, как [css-счетчик](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Counter_Styles/Using_CSS_counters). Попробуй с ним разобраться =)

2022-01-04 18:33 UTC, wrgraff commented on source/sass/blocks/promo.scss
> +    gap: unset;
А почему именно `unset`?
Можно так же обнулять, ставить `auto` и прописывать значение по умолчанию. `unset` же работает еще и с наследованием, что довольно специфично и может привести иногда к неожиданным последствиям, если ты просто хочешь отменить значение.

2022-01-04 18:33 UTC, wrgraff commented on source/sass/blocks/section-title.scss
> +    grid-template-columns: calc((100% - $desktop-width + 20px) / 2) max-content 1fr;
Ладно хоть косинусы не пошли в дело...

2022-01-04 18:33 UTC, wrgraff commented on source/sass/blocks/show-more.scss
> +  background: url("../../img/catalog/catalog-plus.svg");
Не рекомендую привыкать к `background`, лучше писать `background-image`.
Захочешь на планшете поменять картинку, напишешь по привычке составное свойство, и сотрешь все остальные параметры.

2022-01-04 18:33 UTC, wrgraff commented on source/sass/blocks/promo.scss
> +  background: url("../../img/catalog/promo_icon_gift.svg");
Здесь и в `.show-more__title::before` (а может и еще где-то, стоит проверить) путь к картинке указан неправильно

2022-01-05 12:55 UTC, LomaevaVV commented on source/catalog.html
> +  </script>
Перенесла во внешний файл. И подключила в конце.

2022-01-05 12:57 UTC, LomaevaVV commented on source/sass/global/variables.scss
> +$mobole-width: 320px;
спасибо)

2022-01-05 13:11 UTC, LomaevaVV commented on source/sass/blocks/promo.scss
> +  background: url("../../img/catalog/promo_icon_gift.svg");
заменила везде.

2022-01-05 13:13 UTC, LomaevaVV commented on source/sass/blocks/promo.scss
> +  background: url("../../img/catalog/promo_icon_gift.svg");
вот тут неудобство. если хочу не вбивать имя файла, а добавлять через vscode, то надо писать длинный путь. А правильно оставлять короткий в коде. Криво короче, постараюсь запомнить...

2022-01-05 13:14 UTC, LomaevaVV commented on source/sass/blocks/show-more.scss
> +  background: url("../../img/catalog/catalog-plus.svg");
согласна

2022-01-05 13:15 UTC, LomaevaVV commented on source/sass/blocks/section-title.scss
> +    grid-template-columns: calc((100% - $desktop-width + 20px) / 2) max-content 1fr;
)))

2022-01-05 13:26 UTC, LomaevaVV commented on source/sass/blocks/result.scss
Ок, подправила

2022-01-05 13:28 UTC, LomaevaVV commented on source/catalog.html
> +  <script>
сделала, теперь вроде условия выполнены

2022-01-05 14:09 UTC, LomaevaVV commented on source/sass/blocks/promo.scss
> +    gap: unset;
ок, постараюсь запомнить, спасибо

2022-01-05 14:10 UTC, LomaevaVV commented on source/sass/blocks/promo.scss
> +    gap: unset;
почему - сама не знаю)))

2022-01-05 14:25 UTC, LomaevaVV commented on source/sass/blocks/principles.scss
> +    content: "1";
сделала, спасибо! Крутая функция)))

2022-01-05 14:25 UTC, LomaevaVV commented on source/sass/blocks/principles.scss
> +}
принято!

2022-01-05 15:07 UTC, LomaevaVV commented on source/sass/blocks/principles.scss
> +    grid-template-columns: repeat(auto-fill, 230px);
ок, принято

2022-01-05 15:07 UTC, LomaevaVV commented on source/sass/blocks/principles.scss
> +    grid-template-columns: repeat(auto-fill, 230px);
вернула растяжение, вроде справилась
Спасибо за подсказку с сетками в фигме

2022-01-06 11:13 UTC, LomaevaVV commented on source/sass/blocks/page.scss
Вроде сделала, надеюсь так пойдет

2022-01-06 14:01 UTC, LomaevaVV commented on source/sass/blocks/program-type.scss
> +  height: 50px;
Вроде сделала, но блин, криво как-то. В смысле смотрится ничего и двигается "пропорционально, не съезжает ничего". Но везде пришлось немного разными отступами городить. как будто костыли, не нравится мне. Но чет лучше ничего не придумалось

2022-01-06 14:57 UTC, LomaevaVV commented on source/sass/blocks/program-type.scss
> +  display: inline-block;
согласна

2022-01-06 14:57 UTC, LomaevaVV commented on source/sass/blocks/program-type.scss
> +  background: url("../img/index/icon_arrow.svg");
Сделала, так пойдет? Или надо как-то более по-умному?

2022-01-06 15:07 UTC, LomaevaVV commented on source/sass/blocks/example.scss
>    line-height: 18px;
да. точно! спасибо

2022-01-06 15:41 UTC, LomaevaVV commented on source/sass/blocks/images.scss
> +  padding-top: 3px;
согласна((( не думаю на будущее ((( а в лоб

2022-01-06 15:42 UTC, LomaevaVV commented on source/sass/blocks/images.scss
> +    top: 35%;
сделала гридом, да, согласна, не знаю чего я

2022-01-06 15:42 UTC, LomaevaVV commented on source/sass/blocks/images.scss
> +    position: absolute;
починила

2022-01-06 15:43 UTC, LomaevaVV commented on source/sass/blocks/images.scss
> +.images__range {
Сделала и полоску и круг баттоном, хотя наверное можно было оставить див вокруг кнопуи и сделать зеленую линию им, а круг кнопкой. Но пусть будет так

2022-01-06 15:43 UTC, LomaevaVV commented on source/sass/blocks/images.scss
>  }
согласна, не посмотрела стайлгайд. Логично.

2022-01-08 18:22 UTC, wrgraff commented on source/index.html
> +<script src="js/navigation_open_close.js"></script>
Только надо файл подключать внутри `<body>`.
В самом `<html>` может быть только `<head>` и `<body>`. Поэтому, скрипт должен быть уже внутри тела документа.

2022-01-08 18:22 UTC, wrgraff commented on source/sass/blocks/page.scss
> +    background-image: url("../img/index/index_background_desktop.jpg"), linear-gradient(to right, $color-white  50%, $color-green-600 50%);
Тут ок, но на мобильнике он растягивается =)

2022-01-08 18:22 UTC, wrgraff commented on source/sass/blocks/program-type.scss
> +// GREEN CIRCLE
А чего капсом? Вроде же не писала капсом комментарии. Они должны быть в одном стиле

2022-01-08 18:22 UTC, wrgraff commented on source/sass/blocks/program-type.scss
> +  height: 50px;
Такое бывает, если никакой особой логики нет в макете. Его придумали то по сути за тем, чтобы помучить вас самыми странными перестроениями

2022-01-08 18:25 UTC, wrgraff commented on source/sass/blocks/program-type.scss
> +  background: url("../img/index/icon_arrow.svg");
Нет, уже достаточно умно вышло =)

2022-01-08 18:32 UTC, wrgraff commented on source/sass/blocks/result.scss
Я имел ввиду "снижение веса" и "затрачено времени":
<img width="393" alt="изображение" src="https://user-images.githubusercontent.com/37917037/148655490-d6592cd7-9650-48fe-94f7-60d53fdb5e84.png">

Надо бы кстати еще и ширину им подправить, она должна быть по тексту (выравнивание во флексе все может сделать)

2022-01-08 18:33 UTC, wrgraff commented on source/sass/blocks/images.scss
> +.images__range {
Тут по всякому можно, так вполне подойдет

2022-01-08 18:36 UTC, wrgraff commented on source/sass/blocks/images.scss
> +  padding-top: 3px;
Тут скорее вопрос подхода, а не будущего )

2022-01-08 18:43 UTC, wrgraff commented on source/sass/blocks/principles.scss
> +    content: counter(principle_number) "";
А кавычки зачем? )
```suggestion
    content: counter(principle_number);
```

2022-01-08 18:43 UTC, wrgraff commented on source/sass/blocks/promo.scss
> +  background: url("../../img/catalog/promo_icon_gift.svg");
Можно попробовать поискать плагины, которые умеют это фиксить (но не искал, не знаю есть ли они).
или править сборку (но до правки сборки ты вроде как и не дошла еще, так что довольно странно сейчас такую сложную операцию делать)

2022-01-08 18:43 UTC, wrgraff approved these changes

2022-01-08 18:43 UTC, merged